service: aaa-lambda-etl
plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  role: arn:aws:iam::534900169478:role/infinity-cafe-role
  vpc:
    securityGroupIds:
      - sg-00d713bdedcadb4bc
    subnetIds:
      - subnet-093ac2839ae3deb68

functions:
  execute:
    handler: src/app.lambda_handler
    events:
      - s3:
          bucket: aaa-lambda-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: incoming/
            - suffix: .csv
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_USER: ${env:DB_USER}
      DB_PASS: ${env:DB_PASS}
      DB: ${env:DB}
package:
  exclude:
    - .venv/**
    - .vscode/**
    - node_modules/**
