service: aaa-lambda
plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  role: arn:aws:iam::534900169478:role/infinity-cafe-role
  vpc:
    securityGroupIds:
      - sg-00d713bdedcadb4bc
    subnetIds:
      - subnet-093ac2839ae3deb68

functions:
  execute:
    handler: src/app.execute
    events:
      - s3:
          bucket: infinity-cafe-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: incoming/
            - suffix: .csv

package:
  exclude:
    - .venv/**
    - .vscode/**
    - node_modules/**
